CREATE TABLE IF NOT EXISTS books
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200) NOT NULL,
    isbn         VARCHAR(20) UNIQUE NOT NULL,
    publish_year INTEGER,
    edition      VARCHAR(50),
    synopsis     TEXT,
    total_pages  INTEGER,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE books IS 'Table for all the books at the library';
COMMENT ON COLUMN books.id IS 'The book internal identifier (auto-generated)';
COMMENT ON COLUMN books.title IS 'The title of the book (obligatory)';
COMMENT ON COLUMN books.isbn IS 'The book International Standard Book Number (obligatory)';
COMMENT ON COLUMN books.publish_year IS 'The year when the book was published';
COMMENT ON COLUMN books.edition IS 'The book edition';
COMMENT ON COLUMN books.synopsis IS 'The synopsis of the book';
COMMENT ON COLUMN books.total_pages IS 'The amount of pages the book has';
COMMENT ON COLUMN books.created_at IS 'When the book was added to the database';
COMMENT ON COLUMN books.updated_at IS 'When the book was updated in the database';
GRANT SELECT, INSERT, UPDATE, DELETE ON books TO ${librarianRole};
GRANT SELECT ON books TO ${userRole};

CREATE TABLE IF NOT EXISTS authors
(
    id          VARCHAR(36) PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    birth_date  DATE,
    nationality VARCHAR(100),
    biography   TEXT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE authors IS 'Table for all the authors in which their books are at the library';
COMMENT ON COLUMN authors.id IS 'The author UUID internal identifier (generated by the application)';
COMMENT ON COLUMN authors.name IS 'The authors title';
COMMENT ON COLUMN authors.birth_date IS 'The authors birth date';
COMMENT ON COLUMN authors.nationality IS 'The authors nationality';
COMMENT ON COLUMN authors.biography IS 'The authors biography';
COMMENT ON COLUMN authors.created_at IS 'When the author was added in the database';
COMMENT ON COLUMN authors.updated_at IS 'When the author was updated in the database';
GRANT SELECT, INSERT, UPDATE, DELETE ON authors TO ${librarianRole};
GRANT SELECT ON authors TO ${userRole};

CREATE TABLE IF NOT EXISTS book_author
(
    book_id   BIGINT REFERENCES books (id) ON DELETE CASCADE,
    author_id VARCHAR(36) REFERENCES authors (id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, author_id)
);
COMMENT ON TABLE book_author IS 'Join table for N-N relations between books and authors';

CREATE TABLE IF NOT EXISTS users
(
    id              VARCHAR(36) PRIMARY KEY NOT NULL,
    name            VARCHAR(150)        NOT NULL,
    email           VARCHAR(150) UNIQUE NOT NULL,
    phone           VARCHAR(20),
    password        VARCHAR(255) NOT NULL,
    status          VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'blocked')),
    inactive_since  TIMESTAMP DEFAULT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE users IS 'Table for all the users that uses the library';
COMMENT ON COLUMN users.id IS 'The user UUID internal identifier (generated by the application)';
COMMENT ON COLUMN users.name IS 'The user full title';
COMMENT ON COLUMN users.email IS 'The user email';
COMMENT ON COLUMN users.phone IS 'The user phone number';
COMMENT ON COLUMN users.password IS 'The user password (encrypted, obviously)';
COMMENT ON COLUMN users.status IS 'The user library status';
COMMENT ON COLUMN users.inactive_since IS 'The timestamp of when a user was inactive (soft-delete)';
COMMENT ON COLUMN users.created_at IS 'When the user was created';
COMMENT ON COLUMN users.updated_at IS 'When the user was updated';
GRANT SELECT, INSERT, UPDATE ON users TO ${librarianRole};
GRANT SELECT ON users TO ${userRole};

CREATE TABLE IF NOT EXISTS reservations
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id                  BIGINT REFERENCES books (id),
    user_id                  VARCHAR(36) REFERENCES users (id),
    reservation_date         DATE NOT NULL DEFAULT CURRENT_DATE,
    expected_devolution_date DATE NOT NULL,
    devolution_date          DATE,
    status                   VARCHAR(20)   DEFAULT 'active' CHECK (status IN ('active', 'returned', 'overdue')),
    observations             TEXT,
    created_at               TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE reservations IS 'A 1-N table to associate books reservations with who reserved it';
COMMENT ON COLUMN reservations.id IS 'The id of the reservation (auto-generated)';
COMMENT ON COLUMN reservations.book_id IS 'The id of the reserved book';
COMMENT ON COLUMN reservations.user_id IS 'The UUID of the user who reserved the book';
COMMENT ON COLUMN reservations.reservation_date IS 'When the book was reserved';
COMMENT ON COLUMN reservations.expected_devolution_date IS 'When is the book is expected to be returned';
COMMENT ON COLUMN reservations.devolution_date IS 'When the book was really returned';
COMMENT ON COLUMN reservations.status IS 'The status of the reservation';
COMMENT ON COLUMN reservations.observations IS 'Some observations about the reservation';
COMMENT ON COLUMN reservations.created_at IS 'When the reservation was created';
COMMENT ON COLUMN reservations.updated_at IS 'When the reservation was updated';
GRANT SELECT, INSERT, UPDATE, DELETE ON reservations TO ${librarianRole};
GRANT SELECT, INSERT ON reservations TO ${userRole};

CREATE TABLE IF NOT EXISTS roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE
);
COMMENT ON TABLE roles IS 'The roles a user can have for the application';
COMMENT ON COLUMN roles.id IS 'The id of the role (auto-generated)';
COMMENT ON COLUMN roles.name IS 'The role title, with the ROLE_ prefix';
GRANT SELECT ON roles TO ${librarianRole};
GRANT SELECT ON roles TO ${userRole};

CREATE TABLE IF NOT EXISTS user_roles
(
    role_id BIGINT REFERENCES roles(id) ON DELETE CASCADE,
    user_id VARCHAR(36) REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, user_id)
);
COMMENT ON TABLE user_roles IS 'A N-N table relating the users and the roles.';
GRANT SELECT, INSERT, DELETE ON user_roles TO ${librarianRole};